id: test
name: Test
trigger:
  type: startup
action:
  type: chat
  system_prompt: ''
  exit_keyword: exit
  model: claude-sonnet-4-20250514
tools: []
lifecycle:
  type: max_runs
  max_runs: 1
enabled: true
