id: chat
name: Chat
trigger:
  type: startup
action:
  type: chat
  system_prompt: You are a helpful assistant.
  exit_keyword: exit
  model: claude-sonnet-4-20250514
tools:
- simple.add
lifecycle:
  type: max_runs
  max_runs: 1
enabled: true
